project:
  type: book
  output-dir: _book

book:
  title: "Fundamentals of Ecology and Evolutionary Biology"
  subtitle: "BIOS 20153 Lecture Notes"
  author: "Stefano Allesina"
  date: today
  downloads: [pdf]
  chapters:
    - index.qmd
    - 01-unbounded.qmd
    - 02-density_dependence.qmd
    - 03-pathogens.qmd
    - 04-predator_prey.qmd

bibliography: references.bib

format:
  html:
    theme: [flatly, custom.scss]
    number-sections: true
    code-fold: false
  pdf:
    documentclass: scrbook
    number-sections: true
    colorlinks: true

execute:
  freeze: auto
  echo: false
  warning: false
  message: false
