project:
  type: book
  output-dir: _book

book:
  title: "Fundamentals of Ecology and Evolutionary Biology"
  subtitle: "BIOS 20153 Lecture Notes"
  author: "Stefano Allesina"
  date: today
  downloads: [pdf]
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "1. Unbounded Growth"
        href: 01-unbounded.html
      - text: "2. Density Dependence"
        href: 02-density_dependence.html
      - text: "3. Pathogens"
        href: 03-pathogens.html
      - text: "4. Predator-Prey"
        href: 04-predator_prey.html
  chapters:
    - index.qmd
    - 01-unbounded.qmd
    - 02-density_dependence.qmd
    - 03-pathogens.qmd
    - 04-predator_prey.qmd

bibliography: references.bib
reference-section-title: References

format:
  html:
    theme: [flatly, custom.scss]
    number-sections: true
    code-fold: false
    toc: false
  pdf:
    documentclass: scrbook
    number-sections: true
    colorlinks: true

execute:
  freeze: auto
  echo: false
  warning: false
  message: false
